### ISSUE TITLE
Use a valid test_elf.bin for elf image validation

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/linux-loader#41]
The current test_elf.bin is not a valid elf image, which doesn't satisfy the alignment.
It would be better to make the text/data program headers correctly aligned on 4K.

root@0b82237e2682:/linux-loader# readelf -l src/loader/x86_64/elf/test_elf.bin 

Elf file type is EXEC (Executable file)
Entry point 0x100000
There are 2 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000001000 0x0000000000100000 0x0000000000100000
                 0x000000000000001f 0x000000000000001f  R E    0x1000
  LOAD           0x0000000000001020 0x0000000000101020 0x0000000000101020
                 0x000000000000000f 0x000000000000000f  RW     0x1000

 Section to Segment mapping:
  Segment Sections...
   00     .text 
   01     .data

**Comment by lauralt** [comment]
Hi @jiangliu,

I opened a PR which replaces the old image with one in which `p_offset`, `p_vaddr` and `p_paddr` are all page-aligned as it makes the most sense to be like this.

But I'm still curious what exactly did you have in mind when saying `not a valid elf image`. By looking at how we are using the elf image in this crate, I think we would be interested only in the guest physical address (`p_paddr`) to be a multiple of 0x1000, since, for example, we are not using at all the `p_vaddr` addresses. So, wouldn't the following output of `readelf` be okay for our usecase:

```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000001000 0x0000000000100000 0x0000000000100000
                 0x000000000000001d 0x000000000000001d  R E    0x1000
  LOAD           0x0000000000001020 0x0000000000100020 0x0000000000101000
                 0x000000000000000e 0x000000000000000e  RW     0x1000
```
 ?

Also, if we put aside how we use the elf image and think of a correct elf in its usual sense, the elf specification requires that p_vaddr % p_align == p_offset % p_align, where p_align should be a multiple of 0x1000 (or even 0x10000). From this point of view, the old image seems valid and the system knows how to handle segments that have overlapping file pages (but not overlapping content),
which is the current case for our image (reference [here](http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655242___RefHeading___Toc377640650.html)),
That being said, wouldn't be just a matter of performance for `p_offset` and `p_vaddr` to also be individually page-aligned?
Did I misunderstand something? Thanks!

**Comment by aghecenco** [comment]
#50
