### ISSUE TITLE
Fix example in src/lib.rs

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/linux-loader#58]
The example "load an ELF kernel and configure boot params with the PVH protocol" is not working any more because the function "write_bootparams" changed one parameter.

To ensure that the example does not break in the future, we can remove the `ignore` tag, and take the same approach of downloading the resources before running the tests (as we did for `test_load_bzImage`).

**Comment by gabhijit** [comment]
This looks fairly straightforward. Is downloading resources required to be handled in the example? Because the referenced `test_elf.bin` already exists and is added by [this commit](https://github.com/rust-vmm/linux-loader/commit/3cf96c53ed6bfed9c7ca7dcfdbbcd04c86b6dd09).

**Comment by andreeaflorescu** [comment]
If we do not download the resources similarly to how we do it in test_load_bzImage, than this test will fail.

**Comment by gabhijit** [comment]
This test didn't fail without downloading. 

I just did a quick fix for the `write_bootparams` and the test succeeded. So even I was wondering how. It is because the `test_elf.bin` is already there in the repository as per above commit. 

So two questions: 

1. Should we get rid of the downloaded `test_elf.bin` and do something like `test_load_bzimage` ? or
2. Change the example to pass reference to `boot_params`. (With this change alone the test succeeded on my dev machine!)

**Comment by andreeaflorescu** [comment]
I just looked at the example again. It looks like the file is committed to the repository as you said, so we do not need to change it from that respect.

What we should do is option 2 from your comment, and also simplify the example as follows:
- can we remove the functions and have it all as a classic example; if we keep the functions, if any checks would fail, we would not see it
- can we use the path of test_elf.bin instead of using the `include_bytes!` macro?

**Comment by andreeaflorescu** [comment]
Fixed by #59
